spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/malldb
    username: malldbuser
    password: malldbuser
  jpa:
    hibernate:
      ddl-auto: update # none, create-drop(절대X), create(절대X), update, validate
  session:
    timeout: 30m

workhub:
  hello: hello
  jwt-key: 3CxtqcfIGzT0nagO/9Um7+UmRDPyKvsvNSXAQONj9DE=

#  data:
#    web:
#      pageable:
#        one-indexed-parameters: true  # 페이징을 1부터 시작