spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping_mall?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: 1q2w3e4r5t
  jpa:
    hibernate:
      ddl-auto: update # none, create-drop(절대X), create(절대X), update, validate
