### curl 테스트 가능

GET http://localhost:8080/foo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.C5WtxLjy20S-F3GYkAoQ7Eq9KDB1wMw-Fy-GWuRkZlI

### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=wally@naver.com&password=1111


### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "wally",
"email": "wally2@naver.com",
"password": "1111"
}